Added finnish language
MeridianGH/suitbot pull request #20
Opened 2022-05-06 10:55 UTC by karkkijokeri

2022-05-06 10:56 UTC, karkkijokeri commented
I translated it to Finnish xD

2022-05-06 13:22 UTC, MeridianGH requested changes
Nice! Thank you!
Can you do some translations you seem to have missed?
I made comments on the lines in question :)

2022-05-06 13:22 UTC, MeridianGH commented on language/lang/fi-FI.js
> +    amount: { name: 'Määrä', value: (amount) => `${amount} songs` },
Translation missing: songs

2022-05-06 13:22 UTC, MeridianGH commented on language/lang/fi-FI.js
> +  author: 'Viive',
Can you add a dot here? Viive.

2022-05-06 13:22 UTC, MeridianGH commented on language/lang/fi-FI.js
> +    genius: 'Provided by genius.com',
Could you translate this as well?

2022-05-07 09:41 UTC, karkkijokeri commented on language/lang/fi-FI.js
> +  author: 'Viive',
yes

2022-05-07 09:45 UTC, karkkijokeri commented
I fixed everything you asked

2022-05-07 11:29 UTC, MeridianGH commented
Awesome, thanks a lot!

2022-05-07 11:29 UTC, merged